[versions]
agp = "8.5.2"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
compose = "1.7.1"
compose-androidx = "1.7.5"
kotlin = "2.0.21"
maplibre-android-plugins = "3.0.2"
maplibre-ios = "6.8.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.3" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-androidx" }
kermit = { group = "co.touchlab", name = "kermit", version = "2.0.5" }
maplibre-android = { module = "org.maplibre.gl:android-sdk", version = "11.6.1" }
maplibre-android-plugin-annotation = { module = "org.maplibre.gl:android-plugin-annotation-v9", version.ref = "maplibre-android-plugins" }
spatialk-geojson = { group = "io.github.dellisd.spatialk", name = "geojson", version = "0.3.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
spotless = { id = "com.diffplug.spotless", version = "7.0.0.BETA4" }
